# Generated by Django 4.2.1 on 2024-11-09 13:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241109_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='Информация об пользователе'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Изображение пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество лайков'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(
                default=True,
                help_text='Определяет, может ли пользователь войти на сайт администрирования.',
                verbose_name='Статус персонала',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'Пользователь с таким именем уже существует.'},
                help_text='Обязательное условие. 150 символов или меньше. Только буквы, цифры, пробелы и @/./+/-/_.',
                max_length=150,
                unique=True,
                validators=[users.models.ImprovedUnicodeUsernameValidator()],
                verbose_name='username',
            ),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
