# Generated by Django 4.2.1 on 2024-11-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_birthday_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='user',
            name='user_rating',
            field=models.IntegerField(
                default=0,
                help_text='Общий рейтинг автора, учитывающий лайки и дизлайки',
                verbose_name='Рейтинг пользователя',
            ),
        ),
    ]
