# Generated by Django 4.2.1 on 2024-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_total_likes_user_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об пользователе'),
        ),
        migrations.AddField(
            model_name='user',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об пользователе'),
        ),
    ]
