# Generated by Django 4.2.1 on 2024-10-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish', '-id'), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='blog.comment',
                verbose_name='Родитель',
            ),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish', '-id'], name='publish_id_idx'),
        ),
    ]
