# Generated by Django 4.2.1 on 2024-12-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='mark',
            name='nomination_en',
            field=models.CharField(max_length=10, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='mark',
            name='nomination_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок видео'),
        ),
    ]
