# Generated by Django 4.2.1 on 2024-11-04 10:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Основная информация о компании')),
                (
                    'email_contact',
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта для контакта'),
                ),
                (
                    'phone1_num',
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, verbose_name='Мобильный телефон'
                    ),
                ),
                (
                    'phone2_num',
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, verbose_name='Стационарный телефон'
                    ),
                ),
                ('address', models.CharField(blank=True, null=True, verbose_name='Адрес компании')),
                (
                    'latitude',
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата широты'
                    ),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Координата долготы'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Содержание страницы "О нас"',
                'verbose_name_plural': 'Содержание страницы "О нас"',
            },
        ),
    ]
