# Generated by Django 4.2.1 on 2024-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Основная информация о компании'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Основная информация о компании'),
        ),
    ]
